repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--filter-files, --profile, "black"]
        files: ^src/|^tests/
        types: [file, python]


  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.8
        files: ^src/|^tests/
        types: [file, python]
        # args: [--line-length, "99"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # args: ['--ignore=F401,E203']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: ['--maxkb=1500']
      - id: check-merge-conflict
